### PR TITLE
Updated to GH Actions V2

### PR DESCRIPTION
**Pull request by ddsjoberg**
--------------------------------------------------------------------------------

Checklist for PR reviewer

- [ ] PR branch has pulled the most recent updates from main branch. Ensure the pull request branch and your local version match and both have the latest updates from the main branch.
- [ ] If a new function was added, function should be included in `_pkgdown.yml`
- [ ] If a bug was fixed, a unit test was added for the bug check
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features. Review coverage with `withr::with_envvar(new = c("NOT_CRAN" = "true"), covr::report())`. Before you run, begin a fresh R session without any packages loaded. 
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation
- [ ] Has `NEWS.md` been updated with the changes from this pull request under the heading indicating the latest version. If there is an issue associated with the pull request, reference it in parentheses at the end update (see `NEWS.md` for examples).
- [ ] Has the version number been incremented using `usethis::use_version(which = "dev")` 
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge".

### CODE REVIEW

**Review by bailliem — CHANGES_REQUESTED** [review]
Should we remove the action to build the readme on the PR and have this as a manual step and check as part of PR. We had this issue before with building the readme through CI/CD. @epijim and @timtreis

**Review by bailliem — APPROVED** [review]

**Comment by timtreis** [comment]
Just for completeness: Running the README workflow on our PRs before merging is basically our only (not overengineered) way to get up-to-date READMEs without making the main branch no longer write-protected. The README bot just can't push to main because of that. So I don't think it should be generally disabled, just only selectively run on PRs

**Comment by timtreis** [comment]
Oh, okay! That sounds like it was a nightmare do find out :D Is this "done done"? Otherwise we could probably trigger the README workflow after everything else had been done

**Comment by ddsjoberg** [comment]
> Oh, okay! That sounds like it was a nightmare do find out :D Is this "done done"? Otherwise we could probably trigger the README workflow after everything else had been done @timtreis 

I think @bailliem  is making a few minor changes ahead of submitting to CRAN. I am not sure what you mean about triggering the workflow? We added to the checklist to manually build the README, so we won't need the workflow. Also the README build is in the CRAN submission checklist too.

**Comment by timtreis** [comment]
Oh okay, missed the manual build part

**Pull request merged**
