### PR TITLE
Review documentation add_annotation 

### PR DESCRIPTION
**Pull request by bailliem**
* updated example to reflect change to api vr_plot to visR::plot()
* added additional example to display a string comment

### CODE REVIEW

**Comment by dazim** [comment]
Works and explains it well. Do we want to include a primitive example for annotations outside of the plotting area?

**Review by SHAESEN2 — APPROVED** [review]

**Review by timtreis — CHANGES_REQUESTED** [review]
I think we should be coherent in our example in the usage of package::function. Therefore I suggest the following changes:
- Line 29 estimate_KM() -> visR::estimate_KM
- Line 48 get_pvalue() ->  visR::get_pvalue()

Also, for this particular example, it is only necessary to explicitly load `visR` and `survival`. The others are loaded by proxy.

**Comment by bailliem** [comment]
@timtreis  - Can you also check you agree we can remove library(survival) in the examples

**Review by timtreis — APPROVED** [review]
Verified to works on my machine without importing survival. Merge would be fine for me.

**Comment by bailliem** [comment]
Closed merge request.

**Pull request merged**
