### PR TITLE
Documentation for plot function

### PR DESCRIPTION
**Pull request by bailliem**
Add examples to illustrate that visR::plot overrides base plot when visR loads.

### CODE REVIEW

**Comment by bailliem** [comment]
TBD - renaming plot to avoid overriding base plot

**Review by timtreis — CHANGES_REQUESTED** [review]
Hope I'm not being annoying with this :D

- Line 46 -> survival::survfit
- Line 58 -> visR::estimate_KM

**Review by SHAESEN2 — APPROVED** [review]
If we document as such, I am fine with keeping visR::plot

**Review by timtreis — APPROVED** [review]

**Review by bailliem — COMMENTED** [review]
Agree to keep as is, but check experience on possible users

**Pull request merged**
