### PR TITLE
Removing {tidyselect} and {magrittr} dependencies

### LINKED ISSUE #302: Remove {tidyselect} dependency
if you are looking to remove dependencies, you can safely remove tidyselect. It's only being used to access the `tidyselect::any_of()` and `tidyselect::all_of()` functions: both of which are re-exported by dplyr.

### PR DESCRIPTION
**Pull request by ddsjoberg**
- The functions from tidyselect that were being utilized are re-exported by dplyr. Small update to remove the explicit {tidyselect} dependency by using the {dplyr} re-exports.
- The {magrittr} dependency has also been removed by re-exporting the pipe from {dplyr}.
- Remove the redefinition of the `%||%` operator, now merely importing (and not exporting) the operator from {rlang}

closes #302

### CODE REVIEW

**Comment by timtreis** [comment]
Ah, now I realise that `tidyselect` was the branch name ._. I had quite a hard time trying to pull/push just by using the #314 as the ID :D Thank you for the work!

**Comment by ddsjoberg** [comment]
oops, sorry for the confusing naming!! 👀

**Comment by timtreis** [comment]
no no, all good :smile: Just the first PR from a fork that I'm trying to pull

**Comment by timtreis** [comment]
All checks passed anyway, I just wanted to merge in your rename from `man/estimate_CUMINC` to `man/estimate_cuminc`

**Pull request merged**
