### PR TITLE
Updated NEWS with changelog

### PR DESCRIPTION
**Pull request by SHAESEN2**
Quick fixes for readme to remove contributor stats and cover stats (can be accessed through the badge)

### CODE REVIEW

**Comment by SHAESEN2** [comment]
#347 and part of #344

**Comment by SHAESEN2** [comment]
@ddsjoberg do you know how we can restrict building the readme from current branch only?

**Comment by ddsjoberg** [comment]
Awesome! I think the structure should look like this, with one big section header per release and beginning with dev release.

```
# visR (development version)

### New functions
* Highlight specific strata in survival plots using `add_highlight()`.
* Indicate quantiles in survival plots using `add_quantiles()`.
* Estimation and plotting of cumulative competing risks via `estimate_cuminc()` and `visr()`. (#293)

### Utility functions
* `AlignPlots()` has been renamed to `align_plots()`.

# visR 0.2.0

* Initial release. 
```

1. The header `# visR (development version)` will be automatically updated to the correct version number when the version number is incremented with `usethis::use_version()` 
2. The `usethis::use_version()` will also increment the version in the `DESCRIPTION` file. The current version number is `0.2.0`, but since we're in the midst of development it should be bumped to `0.2.0.9000`, indicating a dev version. (Again all versioning will be handled by `usethis::use_version()` )

**Comment by ddsjoberg** [comment]
> @ddsjoberg do you know how we can restrict building the readme from current branch only?

Hmmm, i am not sure. Do you want to chat tomorrow about this?

Also, your note indicates that `README.Rmd` was updates, but i don't see those changes in the git diff. Am I missing something?

**Comment by SHAESEN2** [comment]
> > @ddsjoberg do you know how we can restrict building the readme from current branch only?
> 
> Hmmm, i am not sure. Do you want to chat tomorrow about this?
> 
> Also, your note indicates that `README.Rmd` was updates, but i don't see those changes in the git diff. Am I missing something?

I fixed it. I was changing the wrong file :(

**Comment by ddsjoberg** [comment]
@SHAESEN2 the updates to readme look good and run on my machine without issues. I would suggest the following updates:
- README: Migrate the badges from the markdown table to just be side-by-side. The markdown table takes up a lot of "real estate" on the homepage. But I don't feel like it's adding much information for a visitor to the site. For example, the riskmetric badge already indicates that this is the risk metric, and the column on the right merely re-states that it's a risk metric: same ofr pretty much every badge.
- README: Do you want to add tableone and attrition examples?
- NEWS: The news file doesn't follow the expected structure. 
    - Is there are reason to retain a header for `visR 0.1.1.9004` ?
    - Because this is a development version the first header should be `# visR (development version)`, rather than the unreleased `# visR 0.3.0`.
    - Under the header `# visR 0.1.0`, there is no changelog that is useful for a visitor to the website
    - I would expect one header per CRAN release, and the top one for the current dev version. These headers never need to be manually changed as they are updated when devs call `usethis::use_version()`

**Comment by SHAESEN2** [comment]
> @SHAESEN2 the updates to readme look good and run on my machine without issues. I would suggest the following updates:
> 
> * README: Migrate the badges from the markdown table to just be side-by-side. The markdown table takes up a lot of "real estate" on the homepage. But I don't feel like it's adding much information for a visitor to the site. For example, the riskmetric badge already indicates that this is the risk metric, and the column on the right merely re-states that it's a risk metric: same ofr pretty much every badge.

Done

> * README: Do you want to add tableone and attrition examples?
@cschaerfe is assigned to do so

> * NEWS: The news file doesn't follow the expected structure.
>   
>   * Is there are reason to retain a header for `visR 0.1.1.9004` ?
>   * Because this is a development version the first header should be `# visR (development version)`, rather than the unreleased `# visR 0.3.0`.
>   * Under the header `# visR 0.1.0`, there is no changelog that is useful for a visitor to the website
>   * I would expect one header per CRAN release, and the top one for the current dev version. These headers never need to be manually changed as they are updated when devs call `usethis::use_version()`

Should be fixed. If still not OK, let us then fix it when we do the release and now focus on more important issues.

**Review by bailliem — APPROVED** [review]

**Comment by bailliem** [comment]
@SHAESEN2  and @timtreis  - is this a new issue when running covr::codecovr()

Run covr::codecov()
  covr::codecov()
  shell: /usr/local/bin/Rscript {0}
  env:
    GITHUB_PAT: ***
    R_LIBS_USER: /home/runner/work/_temp/Library
    TZ: UTC
    _R_CHECK_SYSTEM_CLOCK_: FALSE
    NOT_CRAN: true
    RSPM: https://packagemanager.rstudio.com/all/__linux__/focal/latest
Error: Error: Failure in `/tmp/RtmpxC7kJD/R_LIBS358b1[2](https://github.com/openpharma/visR/runs/6073591766?check_suite_focus=true#step:5:2)e829cb/visR/visR-tests/testthat.Rout.fail`
 for (i in seq_along(frames)) { :
  closing unused connection [4](https://github.com/openpharma/visR/runs/6073591766?check_suite_focus=true#step:5:4) (https://raw.githubusercontent.com/vntkumar[8](https://github.com/openpharma/visR/runs/6073591766?check_suite_focus=true#step:5:8)/covid-survival/main/data/final.csv)
Execution halted
Execution halted
Error: Process completed with exit code 1.

**Comment by SHAESEN2** [comment]
> @SHAESEN2 and @timtreis - is this a new issue when running covr::codecovr() It looks like its realted to the interative tutorial - or a test to check if the link is still active.
> 
> Just wanted to check if this is known before adding it as an issue.
> 
> > Run covr::codecov()
> > covr::codecov()
> > shell: /usr/local/bin/Rscript {0}
> > env:
> > GITHUB_PAT: ***
> > R_LIBS_USER: /home/runner/work/_temp/Library
> > TZ: UTC
> > _R_CHECK_SYSTEM_CLOCK_: FALSE
> > NOT_CRAN: true
> > RSPM: https://packagemanager.rstudio.com/all/__linux__/focal/latest
> > Error: Error: Failure in `/tmp/RtmpxC7kJD/R_LIBS358b1[2](https://github.com/openpharma/visR/runs/6073591766?check_suite_focus=true#step:5:2)e829cb/visR/visR-tests/testthat.Rout.fail`
> > for (i in seq_along(frames)) { :
> > closing unused connection [4](https://github.com/openpharma/visR/runs/6073591766?check_suite_focus=true#step:5:4) ([https://raw.githubusercontent.com/vntkumar[8](https://github.com/openpharma/visR/runs/6073591766?check_suite_focus=true#step:5:8)/covid-survival/main/data/final.csv](https://raw.githubusercontent.com/vntkumar%5B8%5D(https://github.com/openpharma/visR/runs/6073591766?check_suite_focus=true#step:5:8)/covid-survival/main/data/final.csv))
> > Execution halted
> > Execution halted
> > Error: Process completed with exit code 1.

Hey Mark,

Can you open a new issue for this? We integrated the tutorial into the develop branch and it might be related to hthis.

**Pull request merged**
