### PR TITLE
Create PR template

### PR DESCRIPTION
**Pull request by SHAESEN2**
#330

### CODE REVIEW

**Review by ddsjoberg — APPROVED** [review]
Looks good to me! (Am I allowed to approve? haha)

**Comment by bailliem** [comment]
@SHAESEN2  and @ddsjoberg  - we should amend both your project access @epijim

**Review by bailliem — COMMENTED** [review]
Looks good

**Comment by ddsjoberg** [comment]
@bailliem @SHAESEN2 it looks like this PR was closed instead of being merged?

**Pull request merged**
