### PR TITLE
GitHub Actions CI - store /docs in new repo

### PR DESCRIPTION
**Pull request by Jonnie-Bevan**
The CI_CD Action will now store the /docs folder in the new https://github.com/openpharma/visR-docs/ repo. 

The action will run checks, build the site and commit to a branch called `copied-docs` in the new repo. 

It does this on push to 
- `github_actions_ci` branch (this can be used as a branch name if looking to edit this Action)
- `develop`
- `master`

Along with this I deleted the /docs folder from this repo, as it's now stored elsewhere.
Also uncommented a line in the README which I think was causing issues before - seems to be fixed now.

Still to do with relation to this PR is change the source of the website to the new repo (in the Settings of the repositories) - this should happen pre-merge of this pull request so the website doesn't break when the docs folder in this repo is deleted, but I thought I should warn people before doing this.

It's worth noting that since the docs get pushed to the `copied-docs` branch (not straight to `master`), that any time the website needs to be updated, someone will need to manually merged that branch into `master` on `visR-docs`. I did this so that the website wouldn't just update every time someone pushes to a test branch - it's not a major concern but it does just mitigate someone breaking things without realising.

### CODE REVIEW

**Comment by epijim** [comment]
Leaving it till Monday as there is another PR going through that changes the API for survival

**Comment by epijim** [comment]
thanks @Jonnie-Bevan!

**Comment by epijim** [comment]
@kawap as an FYI

**Comment by bailliem** [comment]
I've started to a pull request #67  to merge the changes for the API survival repo @epijim , @Jonnie-Bevan  and @kawap .

**Comment by epijim** [comment]
Still on hold @Jonnie-Bevan and @bailliem - let's merge post #67

**Comment by bailliem** [comment]
#67 is merged. Is this branch ready to be deployed? @epijim and @Jonnie-Bevan

**Review by epijim — APPROVED** [review]
need to remove rstantools

**Pull request merged**
