### PR TITLE
Removed last x'd by/when comments

### PR DESCRIPTION
**Pull request by timtreis**
https://github.com/openpharma/visR/issues/280

### CODE REVIEW

**Comment by timtreis** [comment]
If these comments are used for anything in terms of verification, we definitely need a better system that hoping that everyone remembers to update them. Some files don't have them at all, some are definitely outdated (mine included). 

I'll probably implement something like our CRAN-watchdog for the test TOC at the top of these files anyway. I noticed that they're out of sync with the actual tests a lot of times which also seems less than ideal, so I'll just generate them by scraping the actual code. (That's what I wanted the `get_visR_files()` function for). I could probably also write something like this for updating these two fields based on `git blame`. But I think our current system doesn't work.

**Comment by SHAESEN2** [comment]
The system only works if everyone is consistent with it. Currently this is the recommended practice.
Once you have established a better workflow, we can remove the headers. Can you please create an issue for updating the test headers and close this PR?

**Comment by timtreis** [comment]
Can you document these verification procedures and their implied requirements for `visR` in the wiki? In the core meeting, no one was aware of them which is why we said that we could just get rid of the headers. Then I'll come up with a solution that is more robust than hoping that everyone remembers these.

**Comment by SHAESEN2** [comment]
https://github.com/thebioengineer/validation

**Pull request closed without merging**
